apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtube-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: youtube
    app.kubernetes.io/env: dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/KOWSALYADEVI-BL/deployment-of-youtube-main'
    targetRevision: develop
    path: kube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: youtube-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
